namespace GitForest.Infrastructure.Distributed.Grains;

/// <summary>
/// Orleans grain interface for distributed planner execution.
/// Planners are deterministic generators that produce a desired set of Plants from a Plan + repo context.
/// </summary>
public interface IPlannerGrain : IGrainWithStringKey
{
    /// <summary>
    /// Executes the planner to generate plants for a given plan and repository context.
    /// </summary>
    /// <param name="planId">The unique identifier of the plan.</param>
    /// <param name="repositoryPath">The path to the repository.</param>
    /// <returns>A list of plant keys generated by the planner.</returns>
    Task<IReadOnlyList<string>> ExecutePlannerAsync(string planId, string repositoryPath);
    
    /// <summary>
    /// Gets the current status of the planner.
    /// </summary>
    Task<PlannerStatus> GetStatusAsync();
}

/// <summary>
/// Represents the status of a planner grain.
/// </summary>
public record PlannerStatus(
    string PlannerId,
    bool IsRunning,
    DateTime? LastExecutionTime,
    int PlantCount);
